import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:travel_app/constant_widgets/widget_ui_components.dart';

class PrivacyPolicy extends ConsumerWidget {
  const PrivacyPolicy({super.key});

  @override
  Widget build(BuildContext context,WidgetRef ref) {
    return Scaffold(
      appBar: AppBar(
        title: TextWidget(text: "Privacy Policy"),
      ),
      body: const SingleChildScrollView(
        child: Padding(
          padding: EdgeInsets.all(10.0),
          child: Column(
            spacing: 10,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              TextWidget(text: "Last updated: January 26, 2024",isBold: true,fontSize: 16,),
              TextWidget(text: '''
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
          
              ''',isJustify: true,),
              TextWidget(text: "Interpretation",isBold: true,fontSize: 16,),
              TextWidget(text: "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",isJustify: true,),
          
              TextWidget(text: "Interpretation",isBold: true,fontSize: 16,),
              TextWidget(text: '''For the purposes of this Privacy Policy:
          Account means a unique account created for You to access our Service or parts of our Service.
          Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
          Application refers to AI App, the software program provided by the Company.
          Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to AI Travel App. Country refers to: Florida, United States
          Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
          Personal Data is any information that relates to an identified or identifiable individual. Service refers to the Application.
          Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
          Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
          You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
              ''',isJustify: true,),
              TextWidget(text: "Collecting and Using Your Personal Data",isBold: true,fontSize: 16,),
          
              TextWidget(text: "Personal Data",isBold: true,fontSize: 16,),
              TextWidget(text: '''
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          Email address
          First name and last name
          Phone number
          Address, State, Province, ZIP/Postal code, City
          Usage Data
              ''',isJustify: true,),
              TextWidget(text: "Usage Data",isBold: true,fontSize: 16,),
              TextWidget(text: '''Usage Data is collected automatically when using the Service.
          Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
          We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device. Information Collected while Using the Application
          While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission: Information regarding your location
          Information from your Device's phone book (contacts list)
          Pictures and other information from your Device's camera and photo library
              ''',isJustify: true,),
              TextWidget(text: "Law enforcement",isBold: true,fontSize: 16,),
              TextWidget(text: '''
              Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
          
              ''',isJustify: true,),
              TextWidget(text: "Contact us",isBold: true,fontSize: 16,),
              TextWidget(text: '''If you have any questions about this Privacy Policy, You can contact us:
          By email: aitravel@support.com''',isJustify: true,)
          
          
            ],
          ),
        ),
      ),
    );
  }
}
